coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto 
        paths: 
          - "source"
        branches: 
          - master
        if_ci_failed: error
