jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node

    working_directory: ~/korali

    steps:
      - checkout
      - run:
          name: run tests
          command: ./install
  test:
    macos:
      xcode: "10.0.0"

    working_directory: ~/korali

    steps:
      - checkout
      - run:
          name: run tests
          command: ./install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
