version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos

jobs:
  build_linux:
    docker:
      - image: circleci/python:latest
    working_directory: ~/korali
    steps:

      - checkout

      - run:
          name: install MPI
          command: sudo apt-get install mpich;
                   echo 'export MPICXX=mpicxx' >> $BASH_ENV

      - restore_cache:
          keys:
            - cache-linux-v6
            
      - run:
          name: Get developer tools
          command: pushd tools/dev-tools; ./get-tools.sh; popd                  
                   
      - run:
          name: build Korali
          command: timeout 10m ./install

      - save_cache:
          key: cache-linux-v6
          paths:
            - "~/korali/build"
            - "~/korali/tools/dev-tools"
            
      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd
      
      - store_artifacts:
          path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/tests

      - store_artifacts:
          path: ~/korali/docs/test.log

  build_macos:
    macos:
      xcode: "11.4.1"
    working_directory: ~/korali
    steps:

      - checkout

      - restore_cache:
          keys:
            - cache-macos-v6

      - run:
          name: Install wget dependency
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils
                   
      - run:
          name: Get developer tools
          command: pushd tools/dev-tools; ./get-tools.sh; popd       
          
      - run:
          name: build Korali
          command: gtimeout 10m ./install

      - save_cache:
          key: cache-macos-v6
          paths:
            - "~/korali/build"
            - "~/korali/tools/dev-tools"

      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd

      - store_artifacts:
           path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/tests/

