# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/korali

    steps:
      - checkout

      - run:
          name: run tests
          command: ./install

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports
