version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos

jobs:
  build_linux:
    docker:
      - image: circleci/python:3.7.3-node
    working_directory: ~/korali
    steps:

      - checkout

      - restore_cache:
          keys:
            - gsl-dependency
      - run:
          name: build Korali
          command: ./install

      - save_cache:
          key: gsl-dependency
          paths:
            - "~/korali/build/gsl"

  build_macos:
    macos:
      xcode: "10.0.0"
    working_directory: ~/korali
    steps:

      - checkout

      - restore_cache:
          keys:
            - gsl-dependency

      - run:
          name: Install wget dependency
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget

      - run:
          name: build Korali
          command: ./install

      - save_cache:
          key: gsl-dependency
          paths:
            - "~/korali/build/gsl"

