version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos

jobs:
  build_linux:
    docker:
      - image: circleci/python:3.7.3-node
    working_directory: ~/korali
    steps:

      - checkout

      - restore_cache:
          keys:
            - korali-dependencies-linux
      - run:
          name: build Korali
          command: ./install

      - save_cache:
          key: korali-dependencies-linux
          paths:
            - "~/korali/build"
      
      - run:
          name: build webpage
          command: cd docs; ./build.sh

      - run:
          name: deploy webpage
          command: cd docs; ./deploy.sh

      - run:
          name: run tests
          command: cd tests; ./run_all_tests.sh
      
  build_macos:
    macos:
      xcode: "10.0.0"
    working_directory: ~/korali
    steps:

      - checkout

      - restore_cache:
          keys:
            - korali-dependencies-macos

      - run:
          name: Install wget dependency
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget

      - run:
          name: build Korali
          command: ./install

      - save_cache:
          key: korali-dependencies-macos
          paths:
            - "~/korali/build"

      - run:
          name: run tests
          command: cd tests; ./run_all_tests.sh

