version: 2.1

executors:
  ubuntu_openmpi_onednn:
    docker:
      - image: docker.io/cselab/ubuntu_openmpi_onednn:latest
  
  fedora_openmpi:
    docker:
      - image:  docker.io/cselab/fedora_openmpi:latest

jobs:
  build:
    parameters:
      image:
        type: executor
      CC:
        type: string
        default: gcc
      CXX:
        type: string
        default: g++
      buildtype:
        type: string
        default: debug
      buildargs: 
        type: string
        default: ""
    resource_class: xlarge
    executor: << parameters.image >>  
    working_directory: ~/korali
    steps:
      - checkout
      - run:
          name: Build and test and install
          command: |
            CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install -Donednn=true --buildtype=<< parameters.buildtype >>
            ninja -C build
            source tools/helper/set_env.sh build
            meson test -C build
            meson install -C build
      - store_artifacts:
          path: build/meson-logs

workflows:
  ubuntu_openmpi_gcc:
    jobs:
      - build:
          name: release
          image: ubuntu_openmpi_onednn
          buildtype: release

  fedora_openmpi_gcc:
    jobs:
      - build:
          name: release
          image: fedora_openmpi
          buildtype: release
