version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos

jobs:
  build_linux:
    docker:
      - image: circleci/python:latest
    working_directory: ~/korali
    steps:

      - checkout

      - run:
          name: Get Submodules
          command: git submodule init;
                   git submodule update --remote
                   
      - run:
          name: install MPI
          command: sudo apt-get install mpich;
                   echo 'export MPICXX=mpicxx' >> $BASH_ENV

      - restore_cache:
          keys:
            - cache-linux-doxygen-v9
            
      - restore_cache:
          keys:
            - cache-linux-llvm-v9
            
      - restore_cache:
          keys:
            - cache-linux-cmake-v9

      - restore_cache:
          keys:
            - cache-linux-eigen-v9
                  
      - restore_cache:
          keys:
            - cache-linux-gsl-v9
            
      - restore_cache:
          keys:
            - cache-linux-oneDNN-v9
      
      - restore_cache:
          keys:
            - cache-linux-libGP-v9
            
      - restore_cache:
          keys:
            - cache-linux-rtnorm-v9
            
      - run:
          name: Install Doxygen
          command: ./external/install_doxygen.sh
          
      - save_cache:
          key: cache-linux-doxygen-v9
          paths:
            - "~/korali/external/_doxygen/install"
                  
      - run:
          name: Install LLVM (clang-format)
          command: ./external/install_clang.sh
          
      - save_cache:
          key: cache-linux-llvm-v9
          paths:
            - "~/korali/external/_llvm/install"
            
      - run:
          name: Install CMake
          command: ./external/install_CMake.sh
          
      - save_cache:
          key: cache-linux-cmake-v9
          paths:
            - "~/korali/external/CMake/install"

      - run:
          name: Install Eigen
          command: ./external/install_eigen.sh
          
      - save_cache:
          key: cache-linux-eigen-v9
          paths:
            - "~/korali/external/eigen/install"
            
      - run:
          name: Install GSL
          command: ./external/install_gsl.sh
          
      - save_cache:
          key: cache-linux-gsl-v9
          paths:
            - "~/korali/external/GSL/install"
      
      - run:
          name: Install oneDNN
          command: ./external/install_oneDNN.sh
          
      - save_cache:
          key: cache-linux-oneDNN-v9
          paths:
            - "~/korali/external/oneDNN/install"
                                  
      - run:
          name: Install LibGP
          command: ./external/install_libGP.sh
          
      - save_cache:
          key: cache-linux-libGP-v9
          paths:
            - "~/korali/external/libGP/install"
            
      - run:
          name: Install rtnorm
          command: ./external/install_rtnorm.sh
                    
      - save_cache:
          key: cache-linux-rtnorm-v9
          paths:
            - "~/korali/external/rtnorm/install"
            
      - run:
          name: build Korali
          command: ./install --prereqs --jobs=8

      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd

      - store_artifacts:
          path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/docs/test.log

  build_macos:
    macos:
      xcode: "11.4.1"
    working_directory: ~/korali
    steps:

      - checkout
      
      - run:
          name: Get Submodules
          command: git submodule init;
                   git submodule update --remote
                   
      - run:
          name: Install MacOS dependencies
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install gsl;
   
      - restore_cache:
          keys:
            - cache-macos-doxygen-v9
            
      - restore_cache:
          keys:
            - cache-macos-llvm-v9
            
      - restore_cache:
          keys:
            - cache-macos-cmake-v9
           
      - run:
          name: Install Eigen
          command: ./external/install_eigen.sh
          
      - save_cache:
          key: cache-macos-eigen-v9
          paths:
            - "~/korali/external/eigen/install"
        
      - restore_cache:
          keys:
            - cache-macos-eigen-v9
            
      - restore_cache:
          keys:
            - cache-macos-gsl-v9
            
      - restore_cache:
          keys:
            - cache-macos-oneDNN-v9
            
      - restore_cache:
          keys:
            - cache-macos-libGP-v9
            
      - restore_cache:
          keys:
            - cache-macos-rtnorm-v9
      
      - run:
          name: Install Doxygen
          command: ./external/install_doxygen.sh
          
      - save_cache:
          key: cache-macos-doxygen-v9
          paths:
            - "~/korali/external/_doxygen/install"
                  
      - run:
          name: Install LLVM (clang-format)
          command: ./external/install_clang.sh
          
      - save_cache:
          key: cache-macos-llvm-v9
          paths:
            - "~/korali/external/_llvm/install"
            
      - run:
          name: Install CMake
          command: ./external/install_CMake.sh 
          
      - save_cache:
          key: cache-macos-cmake-v9
          paths:
            - "~/korali/external/CMake/install"

      - run:
          name: Install GSL
          command: ./external/install_gsl.sh
          
      - save_cache:
          key: cache-macos-gsl-v9
          paths:
            - "~/korali/external/GSL/install"
      
      - run:
          name: Install oneDNN
          command: ./external/install_oneDNN.sh
          
      - save_cache:
          key: cache-macos-oneDNN-v9
          paths:
            - "~/korali/external/oneDNN/install"
                            
      - run:
          name: Install LibGP
          command: ./external/install_libGP.sh

      - save_cache:
          key: cache-macos-libGP-v9
          paths:
            - "~/korali/external/rtnorm/install"
            
      - run:
          name: Install rtnorm
          command: ./external/install_rtnorm.sh
                    
      - save_cache:
          key: cache-macos-rtnorm-v9
          paths:
            - "~/korali/external/rtnorm/install"
                  
      - run:
          name: build Korali
          command: ./install --prereqs --jobs=4

      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd

      - store_artifacts:
           path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/docs/test.log
