version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux

jobs:
  build_linux:
    docker:
      - image: circleci/python:3.7.3-node
    working_directory: ~/korali
    steps:

      - checkout

      - run:
          name: build webpage
          command: cd docs; timeout 10m ./build.sh

      - run:
          name: deploy webpage
          command: cd docs; ./deploy.sh

