version: 2.1

executors:
  ubuntu_openmpi_onednn:
    docker:
      - image: docker.io/cselab/ubuntu_openmpi_onednn:latest
      
  fedora_openmpi_onednn:
    docker:
      - image: docker.io/cselab/fedora_openmpi_onednn:latest
          
jobs:
  build:
    parameters:
      image:
        type: executor
      CC:
        type: string
        default: gcc
      CXX:
        type: string
        default: g++
      buildtype:
        type: string
        default: debugoptimized
      buildargs: 
        type: string
        default: "-Donednn_path=/usr/local -Dmpi=true"
    resource_class: xlarge
    executor: << parameters.image >>  
    working_directory: ~/korali
    steps:
      - checkout
      - run:
          name: Build and test and install
          command: |
            CC=<< parameters.CC >> CXX=<< parameters.CXX >> meson setup build --prefix=~/test_install << parameters.buildargs >> --buildtype=<< parameters.buildtype >>
            ninja -C build
            source tools/helper/set_env.sh build
            meson install -C build
            meson test -C build
      - store_artifacts:
          path: build/meson-logs

workflows:
  ubuntu_openmpi_gcc:
    jobs:
      - build:
          name: release
          image: ubuntu_openmpi_onednn
          buildtype: release
          
  fedora_openmpi_gcc:
    jobs:
      - build:
          name: release
          image: fedora_openmpi_onednn
          buildtype: release
          
  macos_openmpi_clang:
    jobs:
      - build:
          name: release
          image: macos_openmpi_onednn
          CXX: clang++
          CXX: clang
          buildtype: release
          