version: 2

workflows:
  version: 2
  build:
    jobs:
      - build_linux
      - build_macos

jobs:
  build_linux:
    docker:
      - image: circleci/python:latest
    working_directory: ~/korali
    steps:

      - checkout

      - run:
          name: Get Submodules
          command: git submodule init;
                   git submodule update --remote
                   
      - run:
          name: install MPI
          command: sudo apt-get install mpich;
                   echo 'export MPICXX=mpicxx' >> $BASH_ENV
                   
      - run:
          name: install CMAKE
          command: sudo apt-get install cmake;

      - restore_cache:
          keys:
            - cache-linux-doxygen-v11
            
      - restore_cache:
          keys:
            - cache-linux-llvm-v11
            
      - restore_cache:
          keys:
            - cache-linux-eigen-v11
                  
      - restore_cache:
          keys:
            - cache-linux-gsl-v11
            
      - restore_cache:
          keys:
            - cache-linux-oneDNN-v11
      
      - restore_cache:
          keys:
            - cache-linux-libGP-v11
            
      - restore_cache:
          keys:
            - cache-linux-rtnorm-v11
            
      - run:
          name: Install Doxygen
          command: ./external/install_doxygen.sh
          
      - save_cache:
          key: cache-linux-doxygen-v11
          paths:
            - "~/korali/external/_doxygen/install"
                  
      - run:
          name: Install LLVM (clang-format)
          command: ./external/install_clang.sh
          
      - save_cache:
          key: cache-linux-llvm-v11
          paths:
            - "~/korali/external/_llvm/install"
            
      - run:
          name: Install Eigen
          command: ./external/install_eigen.sh
          
      - save_cache:
          key: cache-linux-eigen-v11
          paths:
            - "~/korali/external/eigen/install"
            
      - run:
          name: Install GSL
          command: ./external/install_gsl.sh
          
      - save_cache:
          key: cache-linux-gsl-v11
          paths:
            - "~/korali/external/GSL/install"
      
      - run:
          name: Install oneDNN
          command: ./external/install_oneDNN.sh
          
      - save_cache:
          key: cache-linux-oneDNN-v11
          paths:
            - "~/korali/external/oneDNN/install"
                                  
      - run:
          name: Install LibGP
          command: ./external/install_libGP.sh
          
      - save_cache:
          key: cache-linux-libGP-v11
          paths:
            - "~/korali/external/libGP/install"
            
      - run:
          name: Install rtnorm
          command: ./external/install_rtnorm.sh
                    
      - save_cache:
          key: cache-linux-rtnorm-v11
          paths:
            - "~/korali/external/rtnorm/install"
            
      - run:
          name: build Korali
          command: cat .install.config.default | sed -e 's/=NO/=YES/g' -e 's/NJOBS=/NJOBS=8 #/g' > install.config; ./install 

      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd

      - store_artifacts:
          path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/tests/test.log

  build_macos:
    macos:
      xcode: "11.4.1"
    working_directory: ~/korali
    steps:

      - checkout
      
      - run:
          name: Get Submodules
          command: git submodule init;
                   git submodule update --remote
                   
      - run:
          name: Install MacOS dependencies
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install wget;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake;
                   HOMEBREW_NO_AUTO_UPDATE=1 brew install gsl;
   
      - restore_cache:
          keys:
            - cache-macos-doxygen-v11
            
      - restore_cache:
          keys:
            - cache-macos-llvm-v11
            
      - restore_cache:
          keys:
            - cache-macos-eigen-v11
            
      - restore_cache:
          keys:
            - cache-macos-gsl-v11
            
      - restore_cache:
          keys:
            - cache-macos-oneDNN-v11
            
      - restore_cache:
          keys:
            - cache-macos-libGP-v11
            
      - restore_cache:
          keys:
            - cache-macos-rtnorm-v11
      
      - run:
          name: Install Doxygen
          command: ./external/install_doxygen.sh
          
      - save_cache:
          key: cache-macos-doxygen-v11
          paths:
            - "~/korali/external/_doxygen/install"
                  
      - run:
          name: Install LLVM (clang-format)
          command: ./external/install_clang.sh
          
      - save_cache:
          key: cache-macos-llvm-v11
          paths:
            - "~/korali/external/_llvm/install"
            
      - run:
          name: Install Eigen
          command: ./external/install_eigen.sh
          
      - save_cache:
          key: cache-macos-eigen-v11
          paths:
            - "~/korali/external/eigen/install"
              
      - run:
          name: Install GSL
          command: ./external/install_gsl.sh
          
      - save_cache:
          key: cache-macos-gsl-v11
          paths:
            - "~/korali/external/GSL/install"
      
      - run:
          name: Install oneDNN
          command: ./external/install_oneDNN.sh
          
      - save_cache:
          key: cache-macos-oneDNN-v11
          paths:
            - "~/korali/external/oneDNN/install"
                            
      - run:
          name: Install LibGP
          command: ./external/install_libGP.sh

      - save_cache:
          key: cache-macos-libGP-v11
          paths:
            - "~/korali/external/libgp/install"
            
      - run:
          name: Install rtnorm
          command: ./external/install_rtnorm.sh
                    
      - save_cache:
          key: cache-macos-rtnorm-v11
          paths:
            - "~/korali/external/rtnorm/install"
                  
      - run:
          name: build Korali
          command: cat .install.config.default | sed -e 's/=NO/=YES/g' -e 's/NJOBS=/NJOBS=4 \#/g' > install.config; ./install

      - run:
          name: run tests
          command: pushd tests; ./run_all_tests.sh; popd

      - store_artifacts:
          path: ~/korali/install.log

      - store_artifacts:
          path: ~/korali/tests/test.log
