site_name: Korali
repo_name: 'cselab/korali'
repo_url: 'https://github.com/cselab/korali'
edit_uri: ''
nav:
  - Home: index.md
  - Features: features.md
  - Installation: install.md
  - Tutorials: tutorials.md
  - User Manual: manual.md
  - Publications: publications.md
  - About Us: aboutus.md
theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.ico'
# Got logo from https://icons8.com/icon/3036/coral
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - admonition
  - codehilite
extra_css:
    - style.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/korali'
    - type: 'twitter'
      link: 'https://twitter.com/EthKorali'
      
google_analytics: ['UA-43580832-2', 'https://www.cse-lab.ethz.ch/korali/']
