site_name: korali
repo_name: 'cselab/skorali'
repo_url: 'https://github.com/cselab/skorali'
edit_uri: ''

nav:
  - Home: index.md
  - Setup:
      - Installing Korali: setup/installation.md
      - Configuration: setup/configuration.md
      - System Requirements: setup/requirements.md
  - Tutorials:
      - 1. Direct Problem: tutorials/direct.md
      - 2. Bayesian Inference: tutorials/bayesian.md
  - User Manual:
      - Introduction: usage/introduction.md
      - Modules:
          - Problem:
              - Direct evaluation: usage/problem/direct.md
              - Bayesian inference: usage/problem/bayesian.md
          - Distributions:
              - Uniform: usage/distributions/uniform.md
              - Gaussian: usage/distributions/gaussian.md
          - Solvers:
              - Optimizers:
                - CMA-ES: usage/solvers/optimizers/cmaes.md
              - Samplers:
                - TMCMC: usage/solvers/samplers/tmcmc.md
          - Conduits:
              - Sequential: usage/conduits/sequential.md
              - Multithreaded: usage/conduits/multithreaded.md
              - UPC++: usage/conduits/upcxx.md
              - MPI: usage/conduits/mpi.md
      - Tools:
          - korali-cxx: usage/tools/korali-cxx.md
          - korali-config: usage/tools/korali-config.md
          - korali-plot: usage/tools/korali-plot.md
      - Plotting:
          - CMA-ES: usage/plotting/plotcmaes.md
          - TMCMC: usage/plotting/plottmcmc.md
  - References: references.md
  - About Us: aboutus.md


theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'pie_chart'


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - admonition
  - codehilite

extra_css:
    - css/extra.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
