site_name: korali
repo_name: 'cselab/skorali'
repo_url: 'https://github.com/cselab/skorali'

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start:
      - Direct problems: quick_start/direct.md
      - Bayesian Inference: quick_start/posterior.md
  - Usage:
      - General Settings: usage/settings.md
      - Problem:
          - Direct evaluation: usage/problem/direct.md
          - Bayesian inference: usage/problem/bayesian.md
      - Distributions:
          - Uniform: usage/distributions/uniform.md
          - Gaussian: usage/distributions/gaussian.md
      - Solvers:
          - Optimizers:
            - CMA-ES: usage/solvers/optimizers/cmaes.md
          - Samplers:
            - TMCMC: usage/solvers/samplers/tmcmc.md
      - Conduits:
          - Sequential: usage/conduits/sequential.md
          - Multithreaded: usage/conduits/multithreaded.md
          - UPC++: usage/conduits/upcxx.md
          - MPI: usage/conduits/mpi.md
  - Tools:
      - configure: tools/configure.md
      - korali-cxx: tools/korali-cxx.md
      - korali-config: tools/korali-config.md
      - korali-plot: tools/korali-plot.md
  - References: references.md


theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'pie_chart'


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - admonition
  - codehilite

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
