site_name: korali
repo_name: 'cselab/skorali'
repo_url: 'https://github.com/cselab/skorali'
edit_uri: ''

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorials:
     - 'A.1 - Optimization': tutorials/optimization/optimization.md
     - 'A.2 - Sampling': tutorials/sampling/sampling.md
     - 'A.3 - Bayesian Inference': tutorials/bayesian/bayesian.md
     - 'B.1 - Checkpoint/Restart': tutorials/bayesian/bayesian.md
     - 'B.2 - Constrained Optimization': tutorials/bayesian/bayesian.md
     - 'B.3 - Distributed Conduit': tutorials/distributed/distributed.md
     - 'B.4 - Nonintrusive Conduit': tutorials/nonintrusive/nonintrusive.md
     - 'C.1 - MPI Model': tutorials/mpi/mpi.md
     - 'C.2 - Nonintrusive Cluster': tutorials/bayesian/bayesian.md
     - 'C.3 - C++/Python Interaction': tutorials/bayesian/bayesian.md
  - User Manual:
      - Korali Basics: usage/basics.md
      - Configuring Korali: usage/config.md
      - Evaluation Types:
          - Direct: usage/evaluation/direct.md
          - Bayesian: usage/evaluation/bayesian.md
      - Variable Distributions:
          - Cauchy: usage/distributions/cauchy.md
          - Exponential: usage/distributions/exponential.md
          - Gamma: usage/distributions/gamma.md
          - Gaussian: usage/distributions/gaussian.md
          - Laplace: usage/distributions/laplace.md
          - Uniform: usage/distributions/uniform.md
      - Solver Methods:
          - Optimizers:
            - CMA-ES: usage/solvers/optimizers/cmaes.md
            - Constrained CMA-ES: usage/solvers/optimizers/ccmaes.md
          - Samplers:
            - TMCMC: usage/solvers/samplers/tmcmc.md
      - Evaluation Conduits:
          - Semi-Intrusive: usage/conduits/semi-intrusive.md
          - Distributed: usage/conduits/distributed.md
          - Nonintrusive: usage/conduits/nonintrusive.md
      - Processing Results: 
          - Export Results: usage/postprocessing/export.md
          - Resume Execution: usage/postprocessing/resume.md
          - Generate Plots: usage/postprocessing/plotting.md
  - Developers:
    - Doxygen: developers/doxygen.md
    - Git Repository: developers/git.md
    - Test Cases: developers/tests.md
  - References: references.md
  - About Us: aboutus.md


theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo: 'images/templogo.png'


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - admonition
  - codehilite

extra_css:
    - style.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
