site_name: korali
repo_name: 'cselab/skorali'
repo_url: 'https://github.com/cselab/skorali'


nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start:
      - C++:
        - Direct problems: quick_start/cxx/direct.md
        - Bayesian Inference: quick_start/cxx/posterior.md
      - Python:
        - Direct problems: quick_start/python/direct.md
        - Bayesian Inference: quick_start/python/posterior.md
  - Documentation:
      - Hierarchy: documentation/hierarchy.md
      - Tools: documentation/tools.md
  - References: references.md


theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'pie_chart'


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - admonition
  - codehilite



extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
