site_name: Korali
#repo_name: 'cselab/korali'
#repo_url: 'https://github.com/cselab/korali'
edit_uri: ''

nav:
  - Home: index.md
  - Installation:
     - 'Installation Guide': install/install.md
     - 'System Requirements': install/requirements.md
     - 'Release Notes': https://github.com/cselab/korali/blob/master/docs/RELEASE-NOTES
     - 'Build Status': install/build.md
  - Tutorials:
     - 'A.1 - Optimization': tutorials/a1-optimization/optimization.md
     - 'A.2 - Sampling': tutorials/a2-sampling/sampling.md
     - 'A.3 - Bayesian Inference': tutorials/a3-bayesian/bayesian.md
     - 'B.1 - Checkpoint/Restart': tutorials/b1-restart/restart.md
     - 'B.2 - Constrained Optimization': tutorials/b2-constrained-optimization/constrained-optimization.md
     #- 'B.3 - Distributed Conduit': tutorials/distributed/distributed.md
     #- 'B.4 - Nonintrusive Conduit': tutorials/nonintrusive/nonintrusive.md
     #- 'C.1 - MPI Model': tutorials/mpi/mpi.md
     #- 'C.2 - Nonintrusive Cluster': tutorials/bayesian/bayesian.md
     #- 'C.3 - C++/Python Interaction': tutorials/bayesian/bayesian.md
  - User Manual:
      - Basics: usage/basics.md
      - Problems:
          - Direct Evaluation: usage/problems/direct.md
          - Bayesian:
            - Direct Likelihood: usage/problems/bayesian/direct.md
            - Reference Likelihood: usage/problems/bayesian/reference.md
      - Solvers:
          - Optimizers:
            - CMA-ES: usage/solvers/cmaes.md
            - DEA: usage/solvers/dea.md
          - Samplers:
            - MCMC: usage/solvers/mcmc.md
            - TMCMC: usage/solvers/tmcmc.md
      - Conduits:
          - Semi-Intrusive: usage/conduits/semi-intrusive.md
          - Distributed: usage/conduits/distributed.md
          - Nonintrusive: usage/conduits/nonintrusive.md
      - Models:
          - Simple: usage/models/simple.md
          - Rerefence: usage/models/reference.md
          - Constraint: usage/models/constraint.md
      - Results:
          - Plotting Results: usage/results/#plotting-results
          - Exporting Results: usage/results/#exporting-results
          - Resume Execution: usage/results/#resume-execution
  - Publications: publications.md
  - About Us: aboutus.md

theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.ico'

# Got logo from https://icons8.com/icon/3036/coral

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - admonition
  - codehilite

extra_css:
    - style.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
google_analytics: ['UA-43580832-2', 'https://www.cse-lab.ethz.ch/korali/']
